
package puzzle.grafika;

import java.awt.Color;
import java.io.IOException;
import puzzle.tlacitka.HraciePole;
import puzzle.hrac.TypHraca;
import puzzle.hrac.ZaciatocnikHrac;

/**
 * GUI kde zadá hráč svoje údaje a vyberie si náročnosť.
 * 
 * @author  Michal Murín
 * @version 2.0  (6 Maj 2020)
 */
public class AplikaciaZaciatocnikGUI extends javax.swing.JFrame {
    private String nickname;
    private int vek;
    /**
     * Vytvor GUI pre začiatočníka.
     * @param nickname
     * @param vek
     * @param typ
     */
    public AplikaciaZaciatocnikGUI(String nickname, int vek, TypHraca typ) {
        this.initComponents();
        this.nickname = nickname;
        this.vek = vek;
        
        this.btgFarby.add(this.rdbCierna);
        this.btgFarby.add(this.rdbCervena);
        this.btgFarby.add(this.rdbZlta);
        
        this.btgHraPrvyKrat.add(this.rdbAno);
        this.btgHraPrvyKrat.add(this.rdbNie);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgFarby = new javax.swing.ButtonGroup();
        btgHraPrvyKrat = new javax.swing.ButtonGroup();
        lblVyberFarbu = new javax.swing.JLabel();
        rdbCierna = new javax.swing.JRadioButton();
        rdbCervena = new javax.swing.JRadioButton();
        rdbZlta = new javax.swing.JRadioButton();
        lblHraPrvyKrat = new javax.swing.JLabel();
        rdbAno = new javax.swing.JRadioButton();
        rdbNie = new javax.swing.JRadioButton();
        btnSpustiHru = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuProgram = new javax.swing.JMenu();
        mniKoniec = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblVyberFarbu.setText("Vyber si svoju obľúbenú farbu");

        rdbCierna.setSelected(true);
        rdbCierna.setText("Čierna");

        rdbCervena.setText("Červená");

        rdbZlta.setText("Žltá");

        lblHraPrvyKrat.setText("Hráš túto hru po prvý krát?");

        rdbAno.setSelected(true);
        rdbAno.setText("Áno");

        rdbNie.setText("Nie");

        btnSpustiHru.setText("Spusti hru");
        btnSpustiHru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpustiHruActionPerformed(evt);
            }
        });

        mnuProgram.setText("Program");

        mniKoniec.setText("Koniec");
        mniKoniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKoniecActionPerformed(evt);
            }
        });
        mnuProgram.add(mniKoniec);

        jMenuBar1.add(mnuProgram);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbNie)
                            .addComponent(rdbAno)
                            .addComponent(lblHraPrvyKrat)
                            .addComponent(rdbZlta)
                            .addComponent(rdbCervena)
                            .addComponent(rdbCierna)
                            .addComponent(lblVyberFarbu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnSpustiHru)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblVyberFarbu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbCierna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbCervena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbZlta)
                .addGap(18, 18, 18)
                .addComponent(lblHraPrvyKrat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbAno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbNie)
                .addGap(18, 18, 18)
                .addComponent(btnSpustiHru)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Ukonči.
     */
    private void mniKoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKoniecActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniKoniecActionPerformed
    /**
     * Spusti hru pre začiatočníka.
     * @throws java.io.IOException
     */
    private void btnSpustiHruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpustiHruActionPerformed
        Color farba = null;
        String oblubenaFarba = null;
        if (this.rdbCierna.isSelected()) {
            farba = Color.BLACK;
            oblubenaFarba = "Čierna";
        }
        if (this.rdbCervena.isSelected()) {
            farba = Color.RED;
            oblubenaFarba = "Červená";
        }
        if (this.rdbZlta.isSelected()) {
            farba = Color.YELLOW;
            oblubenaFarba = "Žltá";
        }
        
        boolean hraPrvyKrat = false;
        if (this.rdbAno.isSelected()) {
            hraPrvyKrat = true;
        }
        if (this.rdbNie.isSelected()) {
            hraPrvyKrat = false;
        }
        
        ZaciatocnikHrac hrac = new ZaciatocnikHrac(this.nickname , this.vek , hraPrvyKrat , oblubenaFarba);
        
        HraciePole hra = new HraciePole(hrac , farba);
        try {
            hra.hraj();
        } catch (IOException ex) {
            System.err.println("Nepodarilo sa spustit hru");
        }
        this.setVisible(false);
        
    }//GEN-LAST:event_btnSpustiHruActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgFarby;
    private javax.swing.ButtonGroup btgHraPrvyKrat;
    private javax.swing.JButton btnSpustiHru;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblHraPrvyKrat;
    private javax.swing.JLabel lblVyberFarbu;
    private javax.swing.JMenuItem mniKoniec;
    private javax.swing.JMenu mnuProgram;
    private javax.swing.JRadioButton rdbAno;
    private javax.swing.JRadioButton rdbCervena;
    private javax.swing.JRadioButton rdbCierna;
    private javax.swing.JRadioButton rdbNie;
    private javax.swing.JRadioButton rdbZlta;
    // End of variables declaration//GEN-END:variables
}
