
package puzzle.grafika;

import java.awt.Color;
import java.io.IOException;
import puzzle.tlacitka.HraciePole;
import puzzle.hrac.PokrocilyHrac;
import puzzle.hrac.TypHraca;
/**
 * GUI kde zadá pokročilý hráč svoje údaje a spustí hru.
 * 
 * @author  Michal Murín
 * @version 2.0  (6 Maj 2020)
 */
public class ApliakciaPokrocilyGUI extends javax.swing.JFrame {
    private String nickname;
    private int vek;
    /**
     * Vytvor GUI pre pokročilého hráča.
     * @param nickname
     * @param vek
     * @param typ
     */
    public ApliakciaPokrocilyGUI(String nickname, int vek, TypHraca typ) {
        this.initComponents();
        this.nickname = nickname;
        this.vek = vek;
        
        this.btgPravidelnyHrac.add(this.rdbAno);
        this.btgPravidelnyHrac.add(this.rdbNie);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgPravidelnyHrac = new javax.swing.ButtonGroup();
        lblNarodnost = new javax.swing.JLabel();
        cbxNarodnost = new javax.swing.JComboBox<>();
        lblPravidelnyHrac = new javax.swing.JLabel();
        rdbAno = new javax.swing.JRadioButton();
        rdbNie = new javax.swing.JRadioButton();
        btnSpustiHru = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuProgram = new javax.swing.JMenu();
        mniKoniec = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblNarodnost.setText("Vyber si svoju národnosť");

        cbxNarodnost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Slovensko", "Česko", "Poľsko", "Rakúsko", "Ukrajina", "Maďarsko", "Nemecko", "USA", "Španielsko", "Rusko", "Taliansko", "Nemecko", "Kuba", "Iné" }));

        lblPravidelnyHrac.setText("Si pravidelný hráč?");

        rdbAno.setSelected(true);
        rdbAno.setText("Áno");

        rdbNie.setText("Nie");

        btnSpustiHru.setText("Spusti hru");
        btnSpustiHru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpustiHruActionPerformed(evt);
            }
        });

        mnuProgram.setText("Program");

        mniKoniec.setText("Koniec");
        mniKoniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKoniecActionPerformed(evt);
            }
        });
        mnuProgram.add(mniKoniec);

        jMenuBar1.add(mnuProgram);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbNie)
                            .addComponent(rdbAno)
                            .addComponent(lblNarodnost)
                            .addComponent(cbxNarodnost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPravidelnyHrac)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnSpustiHru)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNarodnost)
                .addGap(18, 18, 18)
                .addComponent(cbxNarodnost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPravidelnyHrac)
                .addGap(18, 18, 18)
                .addComponent(rdbAno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbNie)
                .addGap(18, 18, 18)
                .addComponent(btnSpustiHru)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Ukonči.
     */
    private void mniKoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKoniecActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniKoniecActionPerformed
    /**
     * Spusti hru pre pokročilého hráča.
     * @throws java.io.IOException
     */
    private void btnSpustiHruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpustiHruActionPerformed
        String narodnost = (String)this.cbxNarodnost.getSelectedItem();
        boolean pravidelnyHrac = false;
        if (this.rdbAno.isSelected()) {
            pravidelnyHrac = true;
        }
        if (this.rdbNie.isSelected()) {
            pravidelnyHrac = false;
        }
        
        PokrocilyHrac hrac = new PokrocilyHrac(this.nickname ,  this.vek, pravidelnyHrac , narodnost);
        HraciePole hra = new HraciePole(hrac , Color.BLACK);
        try {
            hra.hraj();
        } catch (IOException ex) {
            System.err.println("Nepodarilo sa spustit hru");
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnSpustiHruActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgPravidelnyHrac;
    private javax.swing.JButton btnSpustiHru;
    private javax.swing.JComboBox<String> cbxNarodnost;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblNarodnost;
    private javax.swing.JLabel lblPravidelnyHrac;
    private javax.swing.JMenuItem mniKoniec;
    private javax.swing.JMenu mnuProgram;
    private javax.swing.JRadioButton rdbAno;
    private javax.swing.JRadioButton rdbNie;
    // End of variables declaration//GEN-END:variables
}
