
package puzzle.grafika;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import puzzle.hrac.Hrac;
import puzzle.hrac.ZoznamHracov;
import puzzle.vynimky.PridanieHracaException;

/**
 * Výherné GUI ktoré sa zobrazí po vyhratí hry.
 * Vypíše údaje o hráčovi a uloží ho do zoznamu.
 * Vypíše zoznam a je možnosť zoznam vymazať.
 * 
 * @author  Michal Murín
 * @version 2.0  (6 Maj 2020)
 */
public class VyherneOknoGUI extends javax.swing.JFrame {
    private Hrac hrac;
    private ZoznamHracov zoznam;
    private File subor;
    /**
     * Vytvor Výherné GUI.
     * @param hrac
     * @throws java.io.IOException
     */
    public VyherneOknoGUI(Hrac hrac) throws IOException {
        this.initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
        } catch (Exception e) {
            System.out.println("Nepodporovany look and fell");
        }
        this.hrac = hrac;
        this.subor = new File("zoznamHracov.txt");
        if (this.subor.length() == 0) {
            this.zoznam = new ZoznamHracov();
        } else {
            this.zoznam = new ZoznamHracov("zoznamHracov.txt");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGratulacia = new javax.swing.JLabel();
        btnVysledky = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpVysledky = new javax.swing.JTextPane();
        btnUlozHraca = new javax.swing.JButton();
        btnZoznam = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txpVypisZoznamu = new javax.swing.JTextPane();
        btnKoniec = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuZoznam = new javax.swing.JMenu();
        mniVymaz = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblGratulacia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGratulacia.setText("Gratulujem, vyhral si!");

        btnVysledky.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVysledky.setText("Zobraziť výsledky");
        btnVysledky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVysledkyActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txpVysledky);

        btnUlozHraca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUlozHraca.setText("Ulož do zoznamu");
        btnUlozHraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlozHracaActionPerformed(evt);
            }
        });

        btnZoznam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnZoznam.setText("Vypíš zoznam");
        btnZoznam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoznamActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txpVypisZoznamu);

        btnKoniec.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKoniec.setText("Uložiť a ukončiť");
        btnKoniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKoniecActionPerformed(evt);
            }
        });

        mnuZoznam.setText("Zoznam");

        mniVymaz.setText("Vymaž celý zoznam");
        mniVymaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVymazActionPerformed(evt);
            }
        });
        mnuZoznam.add(mniVymaz);

        jMenuBar1.add(mnuZoznam);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKoniec)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnUlozHraca)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnZoznam, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnVysledky)
                        .addComponent(lblGratulacia)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblGratulacia)
                .addGap(18, 18, 18)
                .addComponent(btnVysledky)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUlozHraca)
                    .addComponent(btnZoznam))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKoniec)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Výpíš výsledky hráča.
     */
    private void btnVysledkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVysledkyActionPerformed
        String vysl = this.hrac.toString();
        this.txpVysledky.setText(vysl);
    }//GEN-LAST:event_btnVysledkyActionPerformed
    /**
     * Ulož hráča do súboru.
     */
    private void btnUlozHracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlozHracaActionPerformed
        try {
            this.zoznam.pridajHraca(this.hrac);
        } catch (PridanieHracaException ex) {
            System.out.println("Nepodarilo sa ulozit hraca");
        }
    }//GEN-LAST:event_btnUlozHracaActionPerformed
    /**
     * Vypíš zoznam hráčov.
     */
    private void btnZoznamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoznamActionPerformed
        String vysl = this.zoznam.toString();
        this.txpVypisZoznamu.setText(vysl);
        
        
    }//GEN-LAST:event_btnZoznamActionPerformed
     /**
     * Ulož zoznam do súboru a ukonči program.
     */
    private void btnKoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKoniecActionPerformed
        this.zoznam.ulozZoznamDoSuboru("zoznamHracov.txt");
        System.exit(0);
    }//GEN-LAST:event_btnKoniecActionPerformed
    /**
     * Vymaž celý zoznam.
     */
    private void mniVymazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVymazActionPerformed
        this.zoznam.zmaz();
        
        
        if (this.subor.length() != 0) {
            PrintWriter zapisovac;
            try {
                zapisovac = new PrintWriter(this.subor);
                zapisovac.flush();
                zapisovac.close();
            } catch (FileNotFoundException ex) {
                System.err.println("Nepodarilo sa vymazat zoznam");
            }
                
        }
        
    }//GEN-LAST:event_mniVymazActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKoniec;
    private javax.swing.JButton btnUlozHraca;
    private javax.swing.JButton btnVysledky;
    private javax.swing.JButton btnZoznam;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGratulacia;
    private javax.swing.JMenuItem mniVymaz;
    private javax.swing.JMenu mnuZoznam;
    private javax.swing.JTextPane txpVypisZoznamu;
    private javax.swing.JTextPane txpVysledky;
    // End of variables declaration//GEN-END:variables
}
